#sonata_page_api:
#    resource: '@SonataPageBundle/Resources/config/routing/api.xml'
#    prefix: /

sonata_page_exceptions:
  resource: "@SonataPageBundle/Resources/config/routing/exceptions.php"
  prefix: /
