framework:
  validation:
    email_validation_mode: html5

    # Enables validator auto-mapping support.
    # For instance, basic validation constraints will be inferred from Doctrine's metadata.
    auto_mapping:
      App\Entity\: ["doctrine.orm.default_entity_manager.validator_loader"]

when@test:
  framework:
    validation:
      not_compromised_password: false
