# See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
when@dev: &dev
    zenstruck_foundry:
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

when@test: *dev
